### ISSUE TITLE
Adição de eventListener load e chamada de changeSample()

### ISSUE THREAD

**Issue by testtzlaffe** [ascpenteado/igti#1]
Boa tarde. Estou começando a realmente usar git e github. Vi seu comentário no discord, então resolvi ver seu código, e de quebra aprender na prática como é essa parada de issues aqui no github. 
Achei muito bem organizado seu código e entendi claramente seu raciocínio. Parabéns!
Os únicos pontos que enxergo que poderiam ser incluídos:
1) Encapsular a leitura inicial do campo #sample no window.addEventListener('load', ...........) para ter certeza que o script vai rodar depois que todo o html for renderizado.
2) Talvez chamar a função changeSample(newColor) apenas uma vez, em vez de 3. Por exemplo depois do switch.

Valew brother!

**Comment by ascpenteado** [comment]
Obrigado! Sugestão implementada! :)
